from django.contrib import admin
from .models import *

admin.site.register(logo)
admin.site.register(Footer)
admin.site.register(FooterIcon)
@admin.register(Enquiry)
class EnquiryAdmin(admin.ModelAdmin):
    list_display = ('name', 'email', 'phone', 'service', 'created_at')
    list_filter = ('service', 'created_at')
    search_fields = ('name', 'email', 'phone')
admin.site.register(AboutContent)
admin.site.register(AboutFeature)
admin.site.register(DesignServiceSectionOne)
admin.site.register(DesignServiceSectionTwo)
admin.site.register(DesignServiceSectionThree)
admin.site.register(DesignServiceSectionThreeBox)
admin.site.register(WebsiteDevelopmentSectionOne)
admin.site.register(WebsiteDevelopmentSectionTwo)
admin.site.register(WebsiteDevelopmentSectionThree)
admin.site.register(WebsiteDevelopmentSectionThreeBox)
admin.site.register(WebsiteDevelopmentSectionFour)
admin.site.register(WebsiteDevelopmentSectionFourBox)
admin.site.register(SoftwareDevelopmentSectionOne)
admin.site.register(SoftwareDevelopmentSectionTwo)
admin.site.register(SoftwareDevelopmentSectionThree)
admin.site.register(SoftwareDevelopmentSectionThreeBox)
admin.site.register(HomeSectionOne)
admin.site.register(HomeSectionTwo)
admin.site.register(HomeSectionTwoBox)
admin.site.register(HomeSectionThree)
admin.site.register(HomeSectionThreeBox)
admin.site.register(HomeSectionFour)
admin.site.register(HomeSectionFourServiceBox)
admin.site.register(HomeSectionFive)
admin.site.register(HomeSectionFiveReviewCard)
admin.site.register(HomeSectionSix)
admin.site.register(HomeSectionSixTab)
admin.site.register(HomeSectionSixImage)
admin.site.register(HomeSectionSeven)
admin.site.register(HomeSectionSevenBox)
admin.site.register(SiteSettings)
