# Generated by Django 5.2.6 on 2025-10-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0002_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='linkedin_link',
        ),
        migrations.AddField(
            model_name='footer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='footer_videos/'),
        ),
    ]
