# Generated by Django 5.2.6 on 2025-10-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0005_aboutcontent_aboutfeature_delete_aboutusfeature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutfeature',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='aboutfeature',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='about/icons/'),
        ),
    ]
