# Generated by Django 5.2.6 on 2025-10-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0006_aboutcontent_is_active_aboutfeature_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignServiceSectionOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='design_services/')),
            ],
        ),
    ]
