# Generated by Django 5.2.6 on 2025-10-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0007_designservicesectionone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignServiceSectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='design_features/')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
