# Generated by Django 5.2.6 on 2025-10-28 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0008_designservicesectiontwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignServiceSectionThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignServiceSectionThreeBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='design_section3/images/')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='design_section3/icons/')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='vetriit_app.designservicesectionthree')),
            ],
        ),
    ]
