# Generated by Django 5.2.6 on 2025-10-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0009_designservicesectionthree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designservicesectionthree',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
