# Generated by Django 5.2.6 on 2025-10-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0012_websitedevelopmentsectiontwo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitedevelopmentsectiontwo',
            name='image',
        ),
        migrations.AddField(
            model_name='websitedevelopmentsectiontwo',
            name='icon_class',
            field=models.CharField(default='fa-solid fa-star', help_text='Ex: fa-solid fa-laptop-code', max_length=100),
            preserve_default=False,
        ),
    ]
