# Generated by Django 5.2.6 on 2025-10-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0013_remove_websitedevelopmentsectiontwo_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteDevelopmentSectionThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(help_text='Embed URL (YouTube iframe src URL)')),
                ('title', models.CharField(max_length=200)),
                ('points', models.TextField(blank=True, help_text='Enter points line by line', null=True)),
            ],
        ),
    ]
