# Generated by Django 5.2.6 on 2025-10-29 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0014_websitedevelopmentsectionthree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitedevelopmentsectionthree',
            name='points',
        ),
        migrations.RemoveField(
            model_name='websitedevelopmentsectionthree',
            name='title',
        ),
        migrations.RemoveField(
            model_name='websitedevelopmentsectionthree',
            name='video_url',
        ),
        migrations.CreateModel(
            name='WebsiteDevelopmentSectionThreeBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='webdev/videos/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('points', models.TextField(blank=True, help_text='Add one point per line')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='vetriit_app.websitedevelopmentsectionthree')),
            ],
        ),
    ]
