# Generated by Django 5.2.6 on 2025-10-29 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0015_remove_websitedevelopmentsectionthree_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteDevelopmentSectionFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteDevelopmentSectionFourBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('gradient_start', models.CharField(help_text='Example: #0A933C', max_length=20)),
                ('gradient_end', models.CharField(help_text='Example: #88FF88', max_length=20)),
                ('features', models.TextField(help_text='Write points line by line')),
                ('book_button_link', models.URLField(default='#')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='vetriit_app.websitedevelopmentsectionfour')),
            ],
        ),
    ]
