# Generated by Django 5.2.6 on 2025-10-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0016_websitedevelopmentsectionfour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareDevelopmentSectionOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='software_dev/')),
            ],
        ),
    ]
