# Generated by Django 5.2.6 on 2025-10-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0017_softwaredevelopmentsectionone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareDevelopmentSectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='Ex: fa-solid fa-code', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
