# Generated by Django 5.2.6 on 2025-10-30 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0018_softwaredevelopmentsectiontwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareDevelopmentSectionThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareDevelopmentSectionThreeBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='Ex: fa-solid fa-code', max_length=100)),
                ('title_one', models.CharField(max_length=100)),
                ('title_two', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='software_section_three/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='vetriit_app.softwaredevelopmentsectionthree')),
            ],
        ),
    ]
