# Generated by Django 5.2.6 on 2025-10-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0019_softwaredevelopmentsectionthree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSectionOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('desc1', models.CharField(blank=True, max_length=255, null=True)),
                ('desc2', models.CharField(blank=True, max_length=255, null=True)),
                ('desc3', models.CharField(blank=True, max_length=255, null=True)),
                ('button_text', models.CharField(default='Enquiry Now', max_length=50)),
                ('button_link', models.URLField(default='#')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/section_one/')),
            ],
        ),
    ]
