# Generated by Django 5.2.6 on 2025-10-30 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0020_homesectionone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesectionone',
            name='button_link',
        ),
    ]
