# Generated by Django 5.2.6 on 2025-10-30 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0021_remove_homesectionone_button_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSectionTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black_title', models.CharField(max_length=100)),
                ('green_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSectionTwoClientBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/clients/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_boxes', to='vetriit_app.homesectiontwo')),
            ],
        ),
    ]
