# Generated by Django 5.2.6 on 2025-10-30 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0023_homesectionthree_homesectionthreebox'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSectionFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black_title', models.CharField(max_length=255)),
                ('green_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSectionFourServiceBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='section4_images/')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('points', models.TextField(help_text='Enter each point on a new line')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_boxes', to='vetriit_app.homesectionfour')),
            ],
        ),
    ]
