# Generated by Django 5.2.6 on 2025-10-30 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0024_homesectionfour_homesectionfourservicebox'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSectionFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSectionFiveReviewCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='Ex: fa-solid fa-user-tie', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, help_text='Enter number of stars (1–5)')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cards', to='vetriit_app.homesectionfive')),
            ],
        ),
    ]
