# Generated by Django 5.2.6 on 2025-10-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0025_homesectionfive_homesectionfivereviewcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesectionfivereviewcard',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='homesectionfivereviewcard',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='home/review_icons/'),
        ),
    ]
