# Generated by Django 5.2.6 on 2025-10-31 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0026_remove_homesectionfivereviewcard_icon_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designservicesectiontwo',
            name='icon',
        ),
        migrations.AddField(
            model_name='designservicesectiontwo',
            name='icon_class',
            field=models.CharField(default='fa-solid fa-star', help_text='Example: fa-solid fa-laptop-code', max_length=100),
        ),
    ]
