# Generated by Django 5.2.6 on 2025-10-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0027_remove_designservicesectiontwo_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designservicesectionthreebox',
            name='icon',
        ),
        migrations.AddField(
            model_name='designservicesectionthreebox',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Ex: fa-solid fa-gear or fa-brands fa-figma', max_length=100, null=True),
        ),
    ]
