# Generated by Django 5.2.6 on 2025-10-31 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0028_remove_designservicesectionthreebox_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSectionSix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSectionSixTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='vetriit_app.homesectionsix')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSectionSixImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/section6/')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vetriit_app.homesectionsixtab')),
            ],
        ),
    ]
