# Generated by Django 5.2.6 on 2025-10-31 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0029_homesectionsix_homesectionsixtab_homesectionsiximage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSectionSeven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSectionSevenBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('icon_class', models.CharField(help_text='Ex: fa-solid fa-plus', max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='vetriit_app.homesectionseven')),
            ],
        ),
    ]
