# Generated by Django 5.2.6 on 2025-10-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0030_homesectionseven_homesectionsevenbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homesectionsevenbox',
            old_name='icon_class',
            new_name='icon_open_class',
        ),
        migrations.AddField(
            model_name='homesectionsevenbox',
            name='icon_close_class',
            field=models.CharField(default='fa-solid fa-minus', help_text='Ex: fa-solid fa-minus', max_length=100),
            preserve_default=False,
        ),
    ]
