# Generated by Django 5.2.6 on 2025-10-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0031_rename_icon_class_homesectionsevenbox_icon_open_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Vetri IT', max_length=255)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
            ],
        ),
    ]
