# Generated by Django 5.2.6 on 2025-10-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0032_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designservicesectiontwo',
            name='icon_class',
            field=models.CharField(help_text='Ex: fa-solid fa-lightbulb', max_length=100),
        ),
    ]
