# Generated by Django 5.2.6 on 2025-11-03 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0033_alter_designservicesectiontwo_icon_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homesectiontwo',
            old_name='black_title',
            new_name='title_one',
        ),
        migrations.RenameField(
            model_name='homesectiontwo',
            old_name='green_title',
            new_name='title_two',
        ),
        migrations.CreateModel(
            name='HomeSectionTwoBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homesectiontwo/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='vetriit_app.homesectiontwo')),
            ],
        ),
        migrations.DeleteModel(
            name='HomeSectionTwoClientBox',
        ),
    ]
