# Generated by Django 5.2.6 on 2025-11-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0034_rename_black_title_homesectiontwo_title_one_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homesectionfivereviewcard',
            options={'ordering': ['id'], 'verbose_name': 'Review Box', 'verbose_name_plural': 'Review Boxes (Section Five)'},
        ),
        migrations.RemoveField(
            model_name='homesectionfivereviewcard',
            name='section',
        ),
        migrations.AlterField(
            model_name='homesectionfivereviewcard',
            name='company_name',
            field=models.CharField(default='Unknown Company', max_length=150),
        ),
        migrations.AlterField(
            model_name='homesectionfivereviewcard',
            name='icon',
            field=models.ImageField(default='review_icons/default_user.png', help_text='Client/Reviewer profile picture or logo', upload_to='review_icons/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homesectionfivereviewcard',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
    ]
