# Generated by Django 5.2.6 on 2025-11-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0035_alter_homesectionfivereviewcard_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitedevelopmentsectionfourbox',
            name='book_button_link',
        ),
    ]
