# Generated by Django 5.2.6 on 2025-11-06 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0036_remove_websitedevelopmentsectionfourbox_book_button_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='section_four_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='FooterIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='Example: fa-brands fa-whatsapp', max_length=100)),
                ('link', models.URLField(help_text='Add the URL (e.g. https://instagram.com/yourpage)', max_length=500)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='vetriit_app.footer')),
            ],
        ),
    ]
