# Generated by Django 5.2.6 on 2025-11-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetriit_app', '0037_footer_section_four_heading_footericon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footericon',
            name='link',
            field=models.URLField(help_text='Add the URL (e.g. https://wa.me/8438558627)', max_length=500),
        ),
    ]
